config/routes.rb
Rails.application.routes.draw do
  get '/:locale', to: 'users#home'
  root            to: 'users#home'

  scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do
    mount Ckeditor::Engine => '/ckeditor'
    get 'users/home' => 'users#home'
    get 'users/case_studies' => 'case_studies#index' # make link for edit index and probably add also some users case
    get 'users/services' => 'services#index'
    # devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    devise_for :users do
      get 'users/:id' => 'users#show'
      get 'users' => 'users#index'
    end

    resources :case_studies
    resources :main_contents
    resources :services
    resources :insights
    resources :people

    resources :users, only: %i[index show]
  end
end

app/models/service.rb
# :nodoc
class Service < ApplicationRecord
  has_many :owners
  has_many :people, through: :owners

  with_options if: :title_en_present do |en_set|
    en_set.validates :title_en, presence: true
    en_set.validates :description_en, presence: true
    en_set.validates :category_en, presence: true
    en_set.validates :body_en, presence: true
  end

  with_options if: :title_ru_present do |ru_set|
    ru_set.validates :title_ru, presence: true
    ru_set.validates :description_ru, presence: true
    ru_set.validates :category_ru, presence: true
    ru_set.validates :body_ru, presence: true
  end

  mount_uploader :image, ImageUploader
  self.per_page = 12
end

app/controllers/services_controller.rb
# :nodoc
class ServicesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :find_service, only: %i[edit update show destroy]

  # Index action to render all services
  def index
    if params[:q]
      search_term = params[:q]
      if Rails.env.production?
        @services = Service.where('title_en ilike ? OR description_en ilike ? OR body_en ilike ? OR category_en ilike ? OR title_ru ilike ? OR description_ru ilike ? OR body_ru ilike ? OR category_ru ilike ?',
                                  "%#{search_term}%", '%{search_term}', '%{search_term}', "%#{search_term}%", "%#{search_term}%", '%{search_term}', '%{search_term}', "%#{search_term}%")
        # Change ilike for Postgres to don't make it case sensitive
      else
        @services = Service.where('title_en LIKE ? OR description_en LIKE ? OR body_en LIKE ? OR category_en LIKE ? OR title_ru LIKE ? OR description_ru LIKE ? OR body_ru LIKE ? OR category_ru LIKE ?',
                                  "%#{search_term}%", '%{search_term}', '%{search_term}', "%#{search_term}%", "%#{search_term}%", '%{search_term}', '%{search_term}', "%#{search_term}%")
        # for development and test cases.
      end
    else
      @services = Service.all
    end
    @services = @services.order('created_at DESC').paginate(page: params[:page])
    @main_contents = MainContent.all
  end

  # New action for creating service
  def new
    @service = Service.new
  end

  # Create action saves the service into database
  def create
    @service = Service.new
    # @service.save(service_params)?
    if @service.update_attributes(service_params)
      flash[:notice] = 'Successfully created service!'
      redirect_to service_path(@service)
    else
      flash[:alert] = 'Error creating new service!'
      render :new
    end
  end

  # Edit action retrives the service and renders the edit page
  def edit; end

  # Update action updates the service with the new information
  def update
    if @service.update_attributes(service_params)
      flash[:notice] = 'Successfully updated service!'
      redirect_to([@service])
    else
      flash[:alert] = 'Error updating service!'
      render :edit
    end
  end

  # The show action renders the individual service after retrieving the the id
  def show
    @services = Service.all
  end

  # The destroy action removes the service permanently from the database
  def destroy
    if @service.destroy
      flash[:notice] = 'Successfully deleted service!'
      redirect_to services_path
    else
      flash[:alert] = 'Error updating service!'
    end
  end

  private

  def service_params
    params.require(:service).permit(:image,
                                    :image_url,
                                    :title_en,
                                    :body_en,
                                    :category_en,
                                    :description_en,
                                    :title_ru,
                                    :body_ru,
                                    :category_ru,
                                    :description_ru,
                                    :user_id,
                                    person_ids: []) # do I need user? Test! Test it!
  end

  def find_service
    @service = Service.find(params[:id])
  end
end

app/views/services/_form.html.erb
<%= simple_form_for [@service] do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@service.errors.count, "error")} prohibited this  from being saved:" %>
      </h2>
      <ul>
        <% @service.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>
  <!-- Edit
    ============================================= -->
  <section id="" class="services service singlepage">
    <div class="-wrap">
      <div class="clearfix  description">
        <h2 class="container">
          <%= t 'general.form.english' %>
          <div class="form-group">
            <h4>**<%= t 'general_content.form.allow_content_en' %></h4>
            <%= f.input :title_en, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.input :category_en, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.input :description_en, class: "form-control" %>
          </div>
          <div class="clearfix rowofthree">
            <div class="container bottommargin topmargin article">
              <div class="form-group">
                <%= f.input :body_en, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}} %>
              </div>
            </div>
          </div>
          <%= t 'general.form.russian' %>
          <div class="form-group">
            <h4>**<%= t 'general_content.form.allow_content_ru' %></h4>
            <%= f.input :title_ru, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.input :category_ru, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.input :description_ru, class: "form-control" %>
          </div>
          <div class="clearfix rowofthree">
            <div class="container bottommargin topmargin article">
              <div class="form-group">
                <%= f.input :body_ru, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}} %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <h3><%= t 'services.owners' %></h3>
            <h4>
              <%= f.association :people, include_blank: false, :label_method => lambda { |person| "#{person.first_name_en} #{person.last_name_en}" } %>
            </h4>
          </div>
          <div class="form-group">
            <% if (f.object[:image_url].nil? || f.object[:image_url].empty?) && (f.object[:image].nil? || f.object[:image].empty? ) %>
              <h4>No existing images, please add an image via URL</h4>
            <% else %>
              Preview<br>
              <% if f.object[:image_url] %>
                <%= image_tag(@service.image_url.to_s) %>
              <% end %>
              <h4 class: "form-control">Add new image and ignore this one.</h4>
            <% end %>
          </div>
           <div class="field">
              <%= f.label :image %>
              <h4><%= f.file_field :image %></h4>
          </div>
          <div class="form-group">
            <h3>
              <%= f.input :image_url, class: "form-control"%>
            </h3>
          </div>
          <%= f.hidden_field :user, value: current_user %>
          <div class="form-group">
            <%= f.button :submit %>
          </div>
        </h2>
    </div>
  </section>
  <!-- # end -->
<% end %>

app/views/services/create.html.erb
<h1>CaseStudies#create</h1>
<p>Find me in app/views/case_studies/create.html.erb</p>

app/views/services/destroy.html.erb
<h1>CaseStudiess#destroy</h1>
<p>Find me in app/views/case_studies/destroy.html.erb</p>

app/views/services/edit.html.erb
<!-- Page Title
 ============================================= -->
<section id="page-title">
 <div class="container clearfix">
   <h1>Edit Service</h1>
   <ol class="breadcrumb">
     <!-- /users/:user_id/services/ -->
     <%= link_to 'Back', services_path, 'data-turbolinks':false  %> |
     <li><%= link_to 'Home', root_path, "data-turbolinks":false %></li>
     <li><%= link_to 'Services', users_services_path, "data-turbolinks":false %></li>
   </ol>
 </div>
</section>
<!-- #page-title end -->
<%= render "services/form"  %>

app/views/services/index.html.erb
<!-- Page Title
  ============================================= -->
<section id="page-title">
  <div class="container clearfix">
    <h1><%= t 'services.title' %></h1>
    <ol class="breadcrumb">
      <li><%= link_to t('home.title'), root_path, "data-turbolinks":false %></li>
      <li class="active"><%= t 'services.title'  %></li>
    </ol>
  </div>
</section>
<!-- #page-title end -->

<!--
  ============================================= -->

<section id="" class="services sectionsubhome">
  <div class="-wrap">
    <div class="clearfix  description">
      <h2 class="container">
        <%= tf(@main_contents[1], :title) %>
      </h2>
    </div>
    <div class="sectionsearch clearfix ">
      <nav class="container navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
            <label for="searchwithin"><%= t 'services.search' %></label>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
            <form class="navbar-form navbar-right" role="search">
              <div class="form-group">
                <%= form_with(url: services_path , method: 'get', local: true) do |form| %>
                  <%= form.label :q, t('general_content.search_for') %>
                  <%= form.text_field :q, id: 'q', value: params[:q] %>
                  <button type="submit" class="btn btn-default" placeholder="Search" id="searchwithin">
                    <%= t('general_content.submit') %>
                  </button>
                <% end %>
              </div>
            </form>
          </div>
        </div>
      </nav>
    </div>
    <% @services.each.with_index(1) do |service, index| %>
      <%= ('<div class="clearfix rowofthree">').html_safe if (index == 1 || (index-1) % 3 == 0) %>
        <%= ('<div class="container bottommargin">').html_safe if (index == 1 || (index-1) % 3 == 0) %>
            <div class="col_one_third nobottommargin <%= "col_last" if index % 3 == 0 %>">
              <div class="feature-box media-box">
                  <%= link_to service_path(service), "data-turbolinks":false  do %>
                    <div class="fbox-media">
                      <% unless tf(service, :title).nil? %>
                        <% if service[:image_url].present? || service[:image].present?  %>
                          <%= image_tag(service.image_url.to_s, :width => 350, :height => 218, :crop => :scale, alt: 'Image')%>
                        <% else %>
                          <%= image_tag "services/1.jpg" %>
                        <% end %>
                      <% end %>
                    </div>
                    <div class="fbox-desc">
                      <h3><%= tf(service, :category) unless tf(service, :title).nil?  %> </h3>
                    </div>
                  <% end %>
              </div>
            </div>
        <%= "</div>".html_safe if index % 3 == 0 %>
      <%= "</div>".html_safe if index % 3 == 0 %>
    <% end %>
  </div>
  <!-- pagination -->
  <div class="clearfix rowofthree center">
    <div class="container ">
      <ul class="pagination">
        <div class="flickr_pagination">
          <br>
          <%= will_paginate  @services, :previous_label => '«', :next_label => '»',  "data-turbolinks":false %>
        </div>
      </ul>
    </div>
  </div>
</section>
<!-- #Conent end -->

app/views/services/new.html.erb
<!-- Page Title
 ============================================= -->
<section id="page-title">
 <div class="container clearfix">
   <h1>Create New Service</h1>
   <ol class="breadcrumb">
     <!-- /users/:user_id/services/ -->
     <%= link_to 'Back', services_path, 'data-turbolinks':false  %> |
     <li><%= link_to 'Home', root_path, "data-turbolinks":false %></li>
     <li><%= link_to 'Services', users_services_path, "data-turbolinks":false %></li>
   </ol>
 </div>
</section>
<!-- #page-title end -->

<%= render "services/form" %>

app/views/services/show.html.erb
    <!-- Page Title
      ============================================= -->
    <section id="page-title">
      <div class="container clearfix">
        <h1 class="left"><%= tf(@service, :title) %></h1>
        <ol class="breadcrumb">
          <!-- /users/:user_id/case_studies/:id/edit -->
          <li><%= link_to  t('home.title'), root_path, "data-turbolinks":false %></li>
          <li><%= link_to  t('services.title'), users_services_path, "data-turbolinks":false %></li>
          <li class="active"><%= tf(@service, :title) %></li>
        </ol>
      </div>
    </section>
    <!-- #page-title end -->

      <!-- Content
          ============================================= -->

        <section id="content" class="services service singlepage">
          <div class="content-wrap">
            <div class="clearfix  description">
              <h2 class="container"> <%= raw tf(@service, :description) %></h2>
            </div>

            <div class="clearfix rowofthree">
              <div class="container bottommargin topmargin article">

              <div class="col_two_third">
                 <h2><%= tf(@service, :title) %></h2>
                 <%= raw tf(@service, :body) %>
              </div>
              <div class="col_one_third col_last">
              <h3><%= t 'services.main_lawyer' %></h3>
                <div class="team">
                  <% @service.people.each do |person| %>
                    <%= link_to person_path(person), "data-turbolinks":false  do %>
                      <div class="team-image">                       <% if person[:profile_picture].present? %>
                          <%= image_tag(person.profile_picture.to_s, alt: "#{tf(person, :first_name)} #{tf(person, :last_name)}") %>
                        <% else %>
                          <%= image_tag "people/kuvatov.jpg" %>
                        <% end %>
                      </div>
                      <div class="team-desc">
                        <div class="team-title">
                          <h4><%= "#{tf(person, :first_name)} #{tf(person, :last_name)}" %></h4>
                          <h5><%= tf(person, :title) %></h5>
                    <% end %>
                          <ul>
                            <li>
                              <a href="mailto:#{tf(person, :email)}"> <%= tf(person, :email) %></a>
                            </li>
                            <li><%= person.telephone %></li>
                          </ul>
                        </div>
                      </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>

           <!-- team title  -->
          <div class="clearfix rowofthree">
            <div class="container ">
            <h3><%= t 'services.other' %></h3>

            </div>
          </div>

            <% @services.each.with_index(1) do |service, index| %>
              <%= ('<div class="clearfix rowofthree">').html_safe if (index == 1 || (index-1) % 3 == 0) %>
                <%= ('<div class="container bottommargin">').html_safe if (index == 1 || (index-1) % 3 == 0) %>
                    <div class="col_one_third nobottommargin <%= "col_last" if index % 3 == 0 %>">
                      <div class="feature-box media-box active">
                          <%= link_to service_path( service), "data-turbolinks":false  do %>
                            <div class="fbox-desc">
                              <h3><%= tf(@service, :title) %> </h3>
                            </div>
                          <% end %>
                      </div>
                    </div>
                <%= "</div>".html_safe if index % 3 == 0 %>
              <%= "</div>".html_safe if index % 3 == 0 %>
            <% end %>
          </section>
        <!-- #content end -->
    <!-- # end -->

app/views/services/update.html.erb
<h1>CaseStudies#update</h1>
<p>Find me in app/views/case_studies/update.html.erb</p>