config/routes.rb
Rails.application.routes.draw do
  get '/:locale', to: 'users#home'
  root            to: 'users#home'

  scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do
    mount Ckeditor::Engine => '/ckeditor'
    get 'users/home' => 'users#home'
    get 'users/case_studies' => 'case_studies#index' # make link for edit index and probably add also some users case
    get 'users/services' => 'services#index'
    # devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    devise_for :users do
      get 'users/:id' => 'users#show'
      get 'users' => 'users#index'
    end

    resources :case_studies
    resources :main_contents
    resources :services
    resources :insights
    resources :people

    resources :users, only: %i[index show]
  end
end

app/models/user.rb
# :nodoc
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ROLES = %i[admin user].freeze

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true, uniqueness: true
  # mount_uploader :picture, ImageUploader

  def has_role?(role)
    roles.include?(role)
  end
end

app/controllers/users_controller.rb
# :nodoc
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def index
    @users = User.all
  end

  def show
    @user = current_user
  end

  def home
    @users = User.all
    @user = current_user
    @main_contents = MainContent.all
  end
end

private

def user_params
  params.require(:user).permit(:first_name, :last_name, :username, :role)
end

app/views/users/home.html.erb
  <!-- Page Title
    ============================================= -->
  <section id="page-title">
    <div class="container clearfix">
      <h1><%= t 'home.title' %>, <%= "#{I18n.t('devise.registrations.welcome')}" %></h1>
      <ol class="breadcrumb">
        <li class="active"><%= t 'home.title' %></li>
      </ol>
    </div>
  </section>
  <!-- #page-title end -->

  <!-- Content
      ============================================= -->

    <section id="content" class="casestudies sectionsubhome">
      <div class="content-wrap">
        <div class="clearfix rowofthree">
          <div class="container bottommargin">
            <div class="col_one_third nobottommargin">
              <div class="feature-box media-box">
                <%= link_to users_case_studies_path, "data-turbolinks":false do %>
                  <div class="fbox-media"><%#image_tag "case_studies/1.jpg" %> </div>
                  <div class="fbox-desc">
                    <h5>
                      <%= I18n.t 'case_studies.title' %>
                    </h5>
                    <h3>
                      <%= tf(@main_contents.first, :title) %></h3>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="col_one_third nobottommargin">
              <div class="feature-box media-box">
                <%= link_to users_services_path, "data-turbolinks":false do %>
                  <div class="fbox-media"><%# image_tag "case_studies/2.jpg" %> </div>
                  <div class="fbox-desc">
                    <h5>
                      <%= I18n.t 'services.title' %>
                    </h5>
                    <h3>
                      <%= tf(@main_contents[1], :title)%>
                    </h3>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="col_one_third nobottommargin col_last">
              <div class="feature-box media-box">
                <%= link_to insights_path, "data-turbolinks":false do %>
                  <div class="fbox-media"><%# image_tag "case_studies/3.jpg" %> </div>
                  <div class="fbox-desc">
                    <h5>
                      <%= I18n.t 'insights.title' %>
                    </h5>
                    <h3>
                      <%= tf(@main_contents[2], :title)%>
                    </h3>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <div class="container bottommargin">
            <div class="col_one_third nobottommargin">
              <div class="feature-box media-box">
                <%= link_to people_path, "data-turbolinks":false do %>
                  <div class="fbox-media"><%#image_tag "case_studies/1.jpg" %> </div>
                  <div class="fbox-desc">
                    <h5>
                      <%= I18n.t 'people.title' %>
                    </h5>
                    <h3>
                      <%= tf(@main_contents[3], :title)%>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="col_one_third nobottommargin">
              <div class="feature-box media-box">
                <%= link_to root_path, "data-turbolinks":false do %>
                  <div class="fbox-media"><%# image_tag "case_studies/2.jpg" %> </div>
                  <div class="fbox-desc">
                    <h5>
                      Next model
                    </h5>
                    <h3>
                      Next Title
                    </h3>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="col_one_third nobottommargin col_last">
              <div class="feature-box media-box">
                <%= link_to root_path, "data-turbolinks":false do %>
                  <div class="fbox-media"><%# image_tag "case_studies/3.jpg" %> </div>
                  <div class="fbox-desc">
                    <h5>
                      Next model
                    </h5>
                    <h3>
                      Next Title
                    </h3>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <!-- ANOTHER ROW -->
      </div>
    </section>
    <!-- #content end -->

app/views/users/index.html.erb
<h4 class="container">
  <ul>
    <% @users.each do |user| %>
      <ul>
        <li>Id: <%= user.id %></li>
        <li>Name: <%= user.first_name %></li>
        <li>Username: <%= user.username %></li>
        </br>
      </ul>
    <% end %>
  </ul>
</h4>

app/views/users/show.html.erb
</br>
</br>
<h4 class="container">
  <%= "Id: #{@user.id}" %></br>
  <%= "#{@user.first_name} #{@user.last_name}" %></br>
  <%= "Email: #{@user.email}" %></br>
  <%= "Creation_date: #{@user.created_at.strftime('%b %d, %Y')}" %></br>
  Role or permissions: <%= (@user.role == "admin") ? "Admin" : "Editor" %>
</h4>
</br></br></br></br></br>