config/routes.rb
Rails.application.routes.draw do
  get '/:locale', to: 'users#home'
  root            to: 'users#home'

  scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do
    mount Ckeditor::Engine => '/ckeditor'
    get 'users/home' => 'users#home'
    get 'users/case_studies' => 'case_studies#index' # make link for edit index and probably add also some users case
    get 'users/services' => 'services#index'
    # devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    devise_for :users do
      get 'users/:id' => 'users#show'
      get 'users' => 'users#index'
    end

    resources :case_studies
    resources :main_contents
    resources :services
    resources :insights
    resources :people

    resources :users, only: %i[index show]
  end
end

app/models/main_content.rb
# :nodoc
class MainContent < ApplicationRecord
  validates :title_en, presence: true
  validates :title_ru, presence: true
  self.per_page = 9
end

app/controllers/main_contents_controller.rb
# :nodoc
class MainContentsController < ApplicationController
  before_action :find_main_content, only: %i[edit update show destroy]

  # Index action to render all main_contents
  def index
    @main_contents = MainContent.all
    @main_contents = @main_contents.order('created_at DESC').paginate(page: params[:page])
  end

  # New action for creating main_content
  def new
    user = User.find(current_user.id)
    # this action is not available rigth now
  end

  # Create action saves the main_content into database
  def create
    @main_content = MainContent.new
    if @main_content.save(main_content_params)
      flash[:notice] = 'Successfully created main_content!'
      redirect_to user_main_content_path(@main_content.user, @main_content)
    else
      flash[:alert] = 'Error creating new main_content!'
      render :new
    end
  end

  # Edit action retrives the main_content and renders the edit page
  def edit; end

  # Update action updates the main_content with the new information
  def update
    if @main_content.update_attributes(main_content_params)
      flash[:notice] = 'Successfully updated main_content!'
      redirect_to([@main_content])
    else
      flash[:alert] = 'Error updating main_content!'
      render :edit
    end
  end

  # The show action renders the individual main_content after retrieving the the id
  def show; end

  # The destroy action removes the main_content permanently from the database
  def destroy
    if @main_content.destroy
      flash[:notice] = 'Successfully deleted main_content!'
      redirect_to main_contents_path
    else
      flash[:alert] = 'Error updating main_content!'
    end
  end

  private

  def main_content_params
    params.require(:main_content).permit(:title_en, :title_ru)
  end

  def find_main_content
    @main_content = MainContent.find(params[:id])
  end
end

app/helpers/main_content_helper.rb
module MainContentHelper
end

app/views/main_contents/_form.html.erb
<%= simple_form_for [@main_content] do |f| %>
  <% if @main_content.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@main_content.errors.count, "error")} prohibited this  from being saved:" %>
      </h2>
      <ul>
        <% @main_content.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>
  <!-- Edit ============================================= -->
  <section id="" class="casestudies casestudy singlepage">
    <div class="-wrap">
      <div class="clearfix  description">
        <h2 class="container">
          <div class="form-group">
            <%= t 'general.form.english' %>
            <%= f.input :title_en, class: "form-control" %>
          </div>
        </h2>
        <h2 class="container">
          <div class="form-group">
            <%= t 'general.form.russian' %>
            <%= f.input :title_ru, class: "form-control" %>
          </div>
        </h2>

      <div class="clearfix rowofthree">
        <div class="container bottommargin topmargin article">
          <div class="form-group">
            <%= f.button :submit %>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- # end -->
<% end %>

app/views/main_contents/create.html.erb
<h1>CaseStudies#create</h1>
<p>Find me in app/views/main_conents/create.html.erb</p>

app/views/main_contents/destroy.html.erb
<h1>CaseStudiess#destroy</h1>
<p>Find me in app/views/main_conents/destroy.html.erb</p>

app/views/main_contents/edit.html.erb
<!-- Page Title
 ============================================= -->
<section id="page-title">
 <div class="container clearfix">
   <h1>Edit Main Content</h1>
   <ol class="breadcrumb">
     <!-- /users/:user_id/main_contents/ -->
     <li><%= link_to 'Home', root_path, "data-turbolinks":false %></li>
     <li><%= link_to 'Main Contents', root_path, "data-turbolinks":false %></li>
   </ol>
 </div>
</section>
<!-- #page-title end -->
<%= render "main_contents/form"  %>

app/views/main_contents/index.html.erb
  <!-- Page Title
    ============================================= -->
  <section id="page-title">
    <div class="container clearfix">
      <h1>Main Contents</h1>
      <ol class="breadcrumb">
        <li><%= link_to 'Home', root_path, "data-turbolinks":false %></li>
        <li class="active">Main Contents</li>
      </ol>
    </div>
  </section>
  <!-- #page-title end -->

  <!--============================================= -->

  <section id="" class="casestudies sectionsubhome">
    <div class="-wrap">
      <div class="clearfix  description">
        <h2 class="container">Nulla convallis sollicitudin erat. Nam adipiscing ullamcorper est. Sed id mauris quis erat malesuada tempus. Suspendisse tristique. Nam ut elit. Aenean vitae sem. Quisque diam. Praesent rhoncus hendrerit tortor.</h2>
      </div>
      <div class="sectionsearch clearfix ">
        <nav class="container navbar navbar-default" role="navigation">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
              <label for="searchwithin">Search Main Contents</label>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
              <form class="navbar-form navbar-right" role="search">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search" id="searchwithin">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
              </form>
            </div>
          </div>
        </nav>
      </div>
      <% @main_contents.each.with_index(1) do |main_content, index| %>
        <%= ('<div class="clearfix rowofthree">').html_safe if (index == 1 || (index-1) % 3 == 0) %>
          <%= ('<div class="container bottommargin">').html_safe if (index == 1 || (index-1) % 3 == 0) %>
              <div class="col_one_third nobottommargin <%= "col_last" if index % 3 == 0 %>">
                <div class="feature-box media-box">
                    <%= link_to main_content_path(main_content), "data-turbolinks":false  do %>
                      <div class="fbox-media">
                        <% if main_content[:image_url].present?  %>
                          <%= image_tag(main_content[:image_url], size: "349x218", alt: 'Image') %>
                        <% else %>
                          <%= image_tag "case_studies/1.jpg" %>
                        <% end %>
                      </div>
                      <div class="fbox-desc">
                      </div>
                    <% end %>
                </div>
              </div>
          <%= "</div>".html_safe if index % 3 == 0 %>
        <%= "</div>".html_safe if index % 3 == 0 %>
      <% end %>
    </div>
    <!-- pagination -->
    <div class="clearfix rowofthree center">
      <div class="container ">
        <ul class="pagination">
          <div class="flickr_pagination">
            <br>
            <%= will_paginate  @main_contents, :previous_label => '«', :next_label => '»',  "data-turbolinks":false %>
          </div>
        </ul>
      </div>
    </div>
  </section>
  <!-- #content end -->

app/views/main_contents/new.html.erb
<!-- Page Title
 ============================================= -->
<section id="page-title">
 <div class="container clearfix">
   <h1>Create New Main </h1>
   <ol class="breadcrumb">
     <!-- /users/:user_id/main_conents/ -->
     <%= link_to 'Back', user_case_studies_path(current_user), 'data-turbolinks':false  %> |
     <li><%= link_to 'Home', root_path, "data-turbolinks":false %></li>
     <li><%= link_to 'Main Contents', root_path, "data-turbolinks":false %></li>
   </ol>
 </div>
</section>
<!-- #page-title end -->

<%= render "main_conents/form" %>

app/views/main_contents/show.html.erb
    <div class="-wrap">
      <div class="clearfix  description">
        <h2 class="container">
          <%= raw @main_content.title_en %>
        </h2>
      </div>
    </div>

app/views/main_contents/update.html.erb
<h1>MainContents#update</h1>
<p>Find me in app/views/main_conents/update.html.erb</p>