config/routes.rb
Rails.application.routes.draw do
  get '/:locale', to: 'users#home'
  root            to: 'users#home'

  scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do
    mount Ckeditor::Engine => '/ckeditor'
    get 'users/home' => 'users#home'
    get 'users/case_studies' => 'case_studies#index' # make link for edit index and probably add also some users case
    get 'users/services' => 'services#index'
    # devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    devise_for :users do
      get 'users/:id' => 'users#show'
      get 'users' => 'users#index'
    end

    resources :case_studies
    resources :main_contents
    resources :services
    resources :insights
    resources :people

    resources :users, only: %i[index show]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
  <head>
    <meta name="author" content="Puchkov and Partners, Law Firm Yekaterinburg, Russia" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
    <%= javascript_include_tag 'functions', 'data-turbolinks-track' => false %>

    <!-- Stylesheets
      ============================================= -->
    <link rel="stylesheet" href="https://zacarias.com/dev/puchkovherokucss/css/bootstrap.css" type="text/css" />
    <link rel="stylesheet" href="https://zacarias.com/dev/puchkovherokucss/style.css" type="text/css" />
    <link rel="stylesheet" href="https://zacarias.com/dev/puchkovherokucss/css/dark.css" type="text/css" />
    <link rel="stylesheet" href="https://zacarias.com/dev/puchkovherokucss/css/font-icons.css" type="text/css" />
    <link rel="stylesheet" href="https://zacarias.com/dev/puchkovherokucss/css/animate.css" type="text/css" />
    <link rel="stylesheet" href="https://zacarias.com/dev/puchkovherokucss/css/magnific-popup.css" type="text/css" />
    <link rel="stylesheet" href="https://zacarias.com/dev/puchkovherokucss/css/responsive.css" type="text/css" />
    <link rel="stylesheet" href="https://zacarias.com/dev/puchkovherokucss/css/flacozacarias.css" type="text/css" />
    <link rel="stylesheet" href="https://puchkov-partners.herokuapp.com/assets/css/tonioserna.css" type="text/css" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- TYPEKIT Fonts -->
    <script src="https://use.typekit.net/wox0ksa.js"></script>
    <script>try{Typekit.load({ async: true });}catch(e){}</script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- Document Title
      ============================================= -->
    <title>
      <% if @case_studies || @case_study %>
        <%= t 'case_studies.title' %>
      <% end %>
      <% if @services || @service %>
        <%= t 'services.title' %>
      <% end %>
      <% if @insights || @insight %>
        <%= t 'insights.title' %>
      <% end %>
      <% if @people || @person %>
        <%= t 'people.title' %>
      <% end %>
      <% if @users  %>
        <%= t 'home.title' %>
      <% end %>
      <%= t('general_content.generic_title') %>
    </title>
    <title>Services | Puchkov and Partners Law | Yekaterinburg, Russia</title>
    <%= csrf_meta_tags %>
    <!-- do we need csrf? -->
  </head>

  <body class="stretched">

    <!-- Document Wrapper
      ============================================= -->
    <div id="wrapper" class="clearfix">
      <!-- Header
        ============================================= -->
        <div class = "memberbar ">
          <ul class="mbr-id">
            <% unless current_user.nil? %>
              <li><%= "#{I18n.t('devise.registrations.welcome')}, #{current_user.first_name}" %></li>
              <% unless @service.nil? || current_user.role.nil? %>
                <li> <%= (link_to t("devise.shared.links.edit"), edit_service_path(@service.id), "data-turbolinks":false ) if @service.id %></li>
                <!-- /users/:user_id/case_studies/ -->
                <li><%= link_to 'Back', services_path, "data-turbolinks":false %></li>
              <% end %>
              <% unless @case_study.nil? || @case_study.id.nil? %>
                <li> <%= link_to t("devise.shared.links.edit"), edit_case_study_path(@case_study.id), "data-turbolinks":false %></li>
                <!-- /users/:user_id/case_studies/ -->
                <li><%= link_to t("devise.shared.links.back"), case_studies_path, "data-turbolinks":false %></li>
              <% end %>
              <% unless @insight.nil? || current_user.role.nil? %>
                <li> <%= link_to t("devise.shared.links.edit"), edit_insight_path(@insight.id), "data-turbolinks":false %></li>
                <!-- /users/:user_id/insights/ -->
                <li><%= link_to t("devise.shared.links.back"), insights_path, "data-turbolinks":false %></li>
              <% end %>
              <% unless @person.nil? || current_user.role.nil? || @person.id.nil? %>
                <li> <%= link_to t("devise.shared.links.edit"), edit_person_path(@person.id), "data-turbolinks":false %></li>
                <!-- /users/:user_id/insights/ -->
                <li><%= link_to t("devise.shared.links.back"), people_path, "data-turbolinks":false %></li>
              <% end %>
              <!-- NEW &/OR EDIT TITLE -->
              <% if @services && @main_contents && !current_user.role.nil? %>
                <li> <%= link_to t("devise.shared.links.new"), new_service_path, "data-turbolinks":false %></li>
                <li> <%= link_to t("devise.shared.links.edit"), edit_main_content_path(@main_contents[1]), "data-turbolinks":false %></li>
              <% end %>
              <% if @case_studies && @main_content %>
                <li> <%= link_to t("devise.shared.links.new"), new_case_study_path, "data-turbolinks":false %></li>
                <li> <%= link_to t("devise.shared.links.edit"), edit_main_content_path(@main_content), "data-turbolinks":false unless current_user.role.nil? %></li>
              <% end %>
              <% if @insights && @main_content && !current_user.role.nil? %>
                <li> <%= link_to t("devise.shared.links.new"), new_insight_path, "data-turbolinks":false %></li>
                <li> <%= link_to t("devise.shared.links.edit"), edit_main_content_path(@main_content), "data-turbolinks":false unless current_user.role.nil? %></li>
              <% end %>
              <% if @services && @main_contents && !current_user.role.nil? %>
                <li> <%= link_to t("devise.shared.links.new"), new_service_path, "data-turbolinks":false %></li>
                <li> <%= link_to t("devise.shared.links.edit"), edit_main_content_path(@main_contents[1]), "data-turbolinks":false %></li>
              <% end %>
              <% if @people && !current_user.role.nil? %>
                <li> <%= link_to t("devise.shared.links.new"), new_person_path, "data-turbolinks":false %></li>
              <% end %>
              <!-- ##PENDING Add user main content section path id:1,2...n -->
              <!-- /users/:user_id/case_studies/ -->
              <li><%= link_to t("devise.shared.links.log_out"), destroy_session_path(:user), :method => :delete,"data-turbolinks":false %></li>
            <% else %>
              <li><%= link_to t("devise.shared.links.sign_up"), new_user_registration_path, "data-turbolinks":false %><br /></li>
              <li><%= link_to t("devise.shared.links.sign_in"), user_session_path, "data-turbolinks":false %></li>
            <% end %>
            <li>|<%= link_to 'EN', users_home_path(:locale=>:en), "data-turbolinks":false %></li>
            <li>|<%= link_to 'RU', users_home_path(:locale=>:ru), "data-turbolinks":false %></li>
            <li><% link_to 'DE', users_home_path(:locale=>:de), "data-turbolinks":false %></li>
          </ul>
        </div>

      <header id="header" class="full-header">
        <div id="header-wrap">
          <div class="container clearfix">
            <div id="primary-menu-trigger"><i class="icon-reorder"></i></div>
            <!-- Logo
              ============================================= -->
            <div id="logo">
              <h1><%= link_to t('general_content.basic_title') , root_path(:locale), "data-turbolinks":false %></h1>
            </div>
            <!-- #logo end -->
            <!-- Primary Navigation
              ============================================= -->
            <nav id="primary-menu">
              <ul>
                <li>
                  <%= link_to root_path, "data-turbolinks":false do %>
                    <div>Navigation goes here</div>
                  <% end %>
                </li>
              </ul>

              <!-- Top Search
                ============================================= -->
              <div id="top-search"> <a href="#" id="top-search-trigger"><i class="icon-search3"></i><i class="icon-line-cross"></i></a>
                <form action="../search.html" method="get">
                  <input type="text" name="q" class="form-control" value="" placeholder="Type &amp; Hit Enter..">
                </form>
              </div>
              <!-- #top-search end -->

            </nav>
            <!-- #primary-menu end -->

          </div>
        </div>
      </header>
      <!-- #header end -->
    <!-- #YIELD  -->
    <%= yield %>
    <!-- #YIELD  end -->
    <!-- Footer
      ============================================= -->
    <footer id="footer" class="dark">
      <div class="container">

        <!-- Footer Widgets
          ============================================= -->
        <div class="footer-widgets-wrap clearfix">
          <div class="col_two_third">
            <p>Footer  goes here</p>
          </div>
          <div class="col_one_third col_last">
            <p>Footer  goes here</p>
          </div>
        </div>
        <!-- .footer-widgets-wrap end -->

      </div>

      <!-- Copyrights
        ============================================= -->
      <div id="copyrights">
        <div class="container clearfix">
          <p>Copyright  goes here</p>
        </div>
      </div>
      <!-- #copyrights end -->

    </footer>
    <!-- #footer end -->
  </div>
  <!-- #wrapper end -->

  <!-- Go To Top
    ============================================= -->
  <div id="gotoTop" class="icon-angle-up"></div>

  <!-- External JavaScripts
    ============================================= -->
  <script type="text/javascript" src="https://zacarias.com/dev/puchkovherokucss/js/jquery.js"></script>
  <script type="text/javascript" src="https://zacarias.com/dev/puchkovherokucss/js/plugins.js"></script>

  <!-- Footer Scripts
    ============================================= -->

  <script type="text/javascript" src="https://zacarias.com/dev/puchkovherokucss/js/functions.js"></script>
  </body>
</html>